# Describe your fraud detection model in elaboration . 

The fraud detection is a binary classification problem, where the goal is to predict whether a transaction is fraudulant(1) or non-fraudulant(0). To build an effective fraud detectection model, exploratory data analysis is crucial to understand the data, clean it, and prepare it for modelling. This fraud detection model has been done using Logistic Regression Model and K_Nearest Classifier.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dataset=pd.read_csv("Fraudintern.csv")
dataset

step      type     amount  oldbalanceOrg  newbalanceOrig  \
0           1   PAYMENT    9839.64      170136.00       160296.36   
1           1   PAYMENT    1864.28       21249.00        19384.72   
2           1  TRANSFER     181.00         181.00            0.00   
3           1  CASH_OUT     181.00         181.00            0.00   
4           1   PAYMENT   11668.14       41554.00        29885.86   
...       ...       ...        ...            ...             ...   
1048570    95  CASH_OUT  132557.35      479803.00       347245.65   
1048571    95   PAYMENT    9917.36       90545.00        80627.64   
1048572    95   PAYMENT   14140.05       20545.00         6404.95   
1048573    95   PAYMENT   10020.05       90605.00        80584.95   
1048574    95   PAYMENT   11450.03       80584.95        69134.92   

         oldbalanceDest  newbalanceDest     nameOrig     nameDest  isFraud  \
0                  0.00            0.00  C1231006815  M1979787155        0   
1                  0.00            0.00  C1666544295  M2044282225        0   
2                  0.00            0.00  C1305486145   C553264065        1   
3              21182.00            0.00   C840083671    C38997010        1   
4                  0.00            0.00  C2048537720  M1230701703        0   
...                 ...             ...          ...          ...      ...   
1048570       484329.37       616886.72  C1179511630   C435674507        0   
1048571            0.00            0.00  C1956161225   M668364942        0   
1048572            0.00            0.00  C2037964975  M1355182933        0   
1048573            0.00            0.00  C1633237354  M1964992463        0   
1048574            0.00            0.00  C1264356443   M677577406        0   

         isFlaggedFraud  
0                     0  
1                     0  
2                     0  
3                     0  
4                     0  
...                 ...  
1048570               0  
1048571               0  
1048572               0  
1048573               0  
1048574               0  

[1048575 rows x 11 columns]

In [4]:
dataset= dataset.drop(columns=['nameOrig','nameDest'])
dataset

step      type     amount  oldbalanceOrg  newbalanceOrig  \
0           1   PAYMENT    9839.64      170136.00       160296.36   
1           1   PAYMENT    1864.28       21249.00        19384.72   
2           1  TRANSFER     181.00         181.00            0.00   
3           1  CASH_OUT     181.00         181.00            0.00   
4           1   PAYMENT   11668.14       41554.00        29885.86   
...       ...       ...        ...            ...             ...   
1048570    95  CASH_OUT  132557.35      479803.00       347245.65   
1048571    95   PAYMENT    9917.36       90545.00        80627.64   
1048572    95   PAYMENT   14140.05       20545.00         6404.95   
1048573    95   PAYMENT   10020.05       90605.00        80584.95   
1048574    95   PAYMENT   11450.03       80584.95        69134.92   

         oldbalanceDest  newbalanceDest  isFraud  isFlaggedFraud  
0                  0.00            0.00        0               0  
1                  0.00            0.00        0               0  
2                  0.00            0.00        1               0  
3              21182.00            0.00        1               0  
4                  0.00            0.00        0               0  
...                 ...             ...      ...             ...  
1048570       484329.37       616886.72        0               0  
1048571            0.00            0.00        0               0  
1048572            0.00            0.00        0               0  
1048573            0.00            0.00        0               0  
1048574            0.00            0.00        0               0  

[1048575 rows x 9 columns]

The attributes that play a key role in the prediction process are 
--type, amount, oldbalanceOrg, newbalanceOrig, oldbalanceDest, newbalanceDest, isFraud, isFlaggedFraud

The attributes like nameOrig and nameDest are dropped because they donot contribute in the prediction process

# Data Preprocessing.

In [5]:
a=dataset.iloc[:,1:7].values
b=dataset.iloc[:,7].values
a

array([['PAYMENT', 9839.64, 170136.0, 160296.36, 0.0, 0.0],
       ['PAYMENT', 1864.28, 21249.0, 19384.72, 0.0, 0.0],
       ['TRANSFER', 181.0, 181.0, 0.0, 0.0, 0.0],
       ...,
       ['PAYMENT', 14140.05, 20545.0, 6404.95, 0.0, 0.0],
       ['PAYMENT', 10020.05, 90605.0, 80584.95, 0.0, 0.0],
       ['PAYMENT', 11450.03, 80584.95, 69134.92, 0.0, 0.0]], dtype=object)

In [6]:
b

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [7]:
print(a.shape)

(1048575, 6)


In [8]:
print(b.shape)

(1048575,)


# Encoding the Data

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(a[:,1:5])
a[:,1:5]= imputer.transform(a[:,1:5])

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
a=np.array(ct.fit_transform(a))

# Splitting the dataset

In [11]:
from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test= train_test_split(a,b,test_size=0.2,random_state=0)
a_train[0]

array([0.0, 0.0, 0.0, 0.0, 1.0, 118518.47, 0.0, 0.0, 269761.85, 388280.32],
      dtype=object)

In [12]:
a_test

array([[1.0, 0.0, 0.0, ..., 7657934.33, 480856.38, 416036.59],
       [0.0, 0.0, 0.0, ..., 107008.62, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 502311.35, 0.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 225015.36, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 628.57, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 222089.2, 0.0, 0.0]], dtype=object)

In [13]:
b_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [14]:
b_test

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

# Feature Scaling.

In [15]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
a_train[:,1:]=sc.fit_transform(a_train[:,1:])
a_test[:,1:]=sc.fit_transform(a_test[:,1:])

In [16]:
a_train[0]

array([0.0, -0.744710088571758, -0.08277131627218522, -0.7131029484520298,
       3.326654365415108, -0.15222722032632816, -0.2939543400660556,
       -0.2969648246273572, -0.3088428387284138, -0.3007706829086814],
      dtype=object)

In [17]:
a_test[0]

array([1.0, -0.7413649866316941, -0.08401781366506811, -0.71616188369541,
       -0.2992258512525902, -0.35133943019514624, 2.2265387568273733,
       2.214573370211415, -0.21592669847643592, -0.2875311000211338],
      dtype=object)

Logistic Regression model is used as the dependent variable is a boolean value (1,0)

# Logistic Regression.

In [18]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(a_train,b_train)

C:\Users\Naresh\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

# Fraud Detection

In [19]:
b_pred=classifier.predict(a_test)
print(np.concatenate((b_pred.reshape(len(b_pred),1),b_test.reshape(len(b_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(b_test,b_pred)
print(cm)

[[209491      3]
 [   160     61]]


# Accuracy Score

In [21]:
accuracy_score(b_test,b_pred)

0.9992227546908901

# K-Neighbors Classifier

In [22]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
classifier.fit(a_train,b_train)

KNeighborsClassifier()

# Prediction

In [23]:
b_pred=classifier.predict(a_test)
print(np.concatenate((b_pred.reshape(len(b_pred),1),b_test.reshape(len(b_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


# Confusion Matrix

In [24]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(b_test,b_pred)
print(cm)

[[209476     18]
 [   102    119]]


# Accuracy Score

In [25]:
accuracy_score(b_test,b_pred)

0.9994277948644589

Here are key strategies that a company should implement to both prevent fraud and improve detection during such transitions:
->Adopt Strong Authentication Mechanisms
->Implement Robust Access Control and Monitoring
->Leverage Machine Learning for Fraud Detection
->Secure Software Development and Infrastructure

Here's how we can measure the effictiveness of the strategies that has been implemented by the company
->Key Performance Indicators (KPIs) to Track
    ->Fraud Detection Rate
    ->False Positive Rate
    ->False Negative Rate
    ->Precision, Recall, and F1 Score
-> User and Employee Feedback
->Model Performance Evaluation
->Fraud Simulation Tests